version: '3'

# only runs go app + frontend. bot runs directly on VM, not containerized - more consistent selenium
services:
  ulysses-app:
    build:
        context: ./
        dockerfile: Dockerfile
    volumes:
      - ./src/ulysses.db:/opt/app/ulysses.db
      - ./src/.env:/opt/app/.env
    ports:
      - "3000:3000"
    working_dir: /opt/app
    command: "./ulysses"